[versions]
androidPlugin = "7.4.0"
androidxCamera = "1.2.0"
androidxComposeCompiler = "1.4.0-alpha02"
androidxLifecycle = "2.5.1"
coroutines = "1.6.4"
kotlin = "1.7.20"

[libraries]
# AndroidX
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.6.1" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.0-rc01" }
androidx-camera-core = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidxCamera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidxCamera" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref= "androidxCamera" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version = "2022.12.00" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
androidx-core = { group = "androidx.core", name = "core-ktx", version = "1.9.0" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version = "1.5.4" }
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.3.0-rc01" }

# KotlinX
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version = "1.4.1" }

# TensorFlow
tensorflow-gpu = { group = "org.tensorflow", name = "tensorflow-lite-gpu", version = "2.11.0" }
tensorflow-gpuDelegate = { group = "org.tensorflow", name = "tensorflow-lite-gpu-delegate-plugin", version = "0.4.3" }
tensorflow-taskVision = { group = "org.tensorflow", name = "tensorflow-lite-task-vision", version = "0.4.3" }

# Others
coil = { group = "io.coil-kt", name = "coil", version = "2.2.2" }
materialDesign = { group = "com.google.android.material", name = "material", version = "1.7.0" }

# Build Configuration
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidPlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidPlugin" }
android-library = { id = "com.android.library", version.ref = "androidPlugin" }
dependencyVersions = { id = "com.github.ben-manes.versions", version = "0.44.0" }
gradleDoctor = { id = "com.osacky.doctor", version = "0.8.1" }
gradleDownload = { id = "de.undercouch.download", version = "5.3.0" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
